### PR TITLE
added line from dshivaraintel

### PR DESCRIPTION
**Pull request by dilipshivaraju**
Added a extra line from dshivaraintel

### CODE REVIEW

**Review by dilipshivaraju — COMMENTED** [review]
Can you please remove "from" from "added line from dshivara_intel"?

**Comment by dshivaraju** [comment]
Can you please remove "from" from "added line from dshivara_intel"?

**Comment by dshivaraju** [comment]
Made the necessary changes.

**Comment by dilipshivaraju** [comment]
Made the necessary changes

**Pull request merged**
